## Logistic Regression for Multiclass Classification Problem

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [3]:
X,y = make_classification(n_samples=1000 ,n_features=10 ,n_classes=3,n_informative=3 ,random_state=76)

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=.30,random_state=65)

In [5]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(multi_class='ovr',n_jobs=-1)
logistic.fit(X_train,y_train)
y_pred = logistic.predict(X_test)

c:\Users\SHIVAM KUMAR\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [6]:
# Performance metrics

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [7]:
score = accuracy_score(y_test,y_pred)
print(score)
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.6714285714285714
[[154  39  46]
 [ 40 159  28]
 [ 54  23 157]]
              precision    recall  f1-score   support

           0       0.62      0.64      0.63       239
           1       0.72      0.70      0.71       227
           2       0.68      0.67      0.68       234

    accuracy                           0.67       700
   macro avg       0.67      0.67      0.67       700
weighted avg       0.67      0.67      0.67       700

