## Logistic Regression

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
from sklearn.datasets import make_classification


In [5]:
# Create a dataset
X,y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42)

In [6]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    0.964799 -0.066449  0.986768 -0.358079  0.997266  1.181890 -1.615679   
1   -0.916511 -0.566395 -1.008614  0.831617 -1.176962  1.820544  1.752375   
2   -0.109484 -0.432774 -0.457649  0.793818 -0.268646 -1.836360  1.239086   
3    1.750412  2.023606  1.688159  0.006800 -1.607661  0.184741 -2.619427   
4   -0.224726 -0.711303 -0.220778  0.117124  1.536061  0.597538  0.348645   
..        ...       ...       ...       ...       ...       ...       ...   
995 -1.367638  1.462255 -1.154918 -0.290454 -0.413424  0.032396  1.545490   
996 -1.514876 -3.221016 -1.300744  0.395599 -0.527994  1.353069  1.777506   
997  1.674633  1.754933  1.586154  0.018402 -1.514470  0.321593 -2.417694   
998 -0.778609 -0.835689 -0.194842  1.097220  0.180071 -0.272933 -0.533188   
999  0.248454 -1.003439  0.360460 -0.331352  1.389764 -1.345210 -0.740875   

            7         8         9  
0   -1.210161 -0.628077  1.227274  
1   -0.984534  0.363896  0.209470  
2   -0.246383 -1.058145 -0.297376  
3   -0.357445 -1.473127 -0.190039  
4   -0.939156  0.175915  0.236224  
..        ...       ...       ...  
995  1.428760  1.687092  1.072542  
996 -1.680870  1.798510  0.034272  
997  0.692723 -1.503850  0.225264  
998 -0.497354  2.472138  0.867187  
999  0.773240  0.185734  1.416412  

[1000 rows x 10 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=.30, random_state=42)

In [8]:
#Model training
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()

In [9]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [10]:
y_pred = logistic.predict(X_test)
print(y_pred)

[0 1 0 1 0 1 0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 0 1 0 0 1 0 0 0 1 1 1 0 0 0 0 1
 1 1 1 0 1 1 0 0 1 1 1 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 0
 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 0 1 1
 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1
 0 0 0 0 1 1 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1 0 0
 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1
 0 1 0 1 1 0 0 1 1 1 0 1 1 1 0 1 0 1 0 0 1 0 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1
 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 1 1 0
 0 0 1 1 1 1 1 1 0 0 1 0 0 1 0 0 0 0 1 1 1 1 0 1 1 1 0 0 1 1 0 1 1 0 1 1 1
 1 1 1 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0
 1 1 1 1 1 0 0 0 1 1 0 0 1 1 1 0 1 1 0 0 1 1 1 1 1 0 0 1 0 0 1 0 1 0 1 0 1
 1 1 0 0 1 0 1 1 0 0 0 1 0 1 0 1 0 0 1 1 1 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 1
 1 0 0 1 1 0 0 1 1 0 1 1 

In [11]:
logistic.predict_proba(X_test)

array([[0.89410793, 0.10589207],
       [0.06880015, 0.93119985],
       [0.59232694, 0.40767306],
       ...,
       [0.03254986, 0.96745014],
       [0.84651622, 0.15348378],
       [0.00243599, 0.99756401]], shape=(700, 2))

In [12]:
# See the performance matrics
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [13]:
score = accuracy_score(y_test,y_pred)
print(score)
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.8571428571428571
[[293  50]
 [ 50 307]]
              precision    recall  f1-score   support

           0       0.85      0.85      0.85       343
           1       0.86      0.86      0.86       357

    accuracy                           0.86       700
   macro avg       0.86      0.86      0.86       700
weighted avg       0.86      0.86      0.86       700



## Hyperparameter Tuning And Corss Validation

In [14]:
model = LogisticRegression()
penalty = ['l1','l2','elasticnet']
c_values = [100, 10, 2.9, .3, .72]
solver = ['newton-cg', 'newton-cholesky', 'sag','saga']

In [15]:
param = dict(penalty=penalty,C=c_values,solver=solver)

In [16]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold(n_splits=5)

In [17]:
# GridSearchCV
from sklearn.model_selection import GridSearchCV
cv = StratifiedKFold()
grid = GridSearchCV(estimator = model, param_grid=param_grid, scoring="accuracy",cv = cv,n_jobs=-1)

In [ ]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [100, 10, 2.9, 0.3, 0.72], 'penalty': ['l2'],
                          'solver': ['newton-cg', 'newton-cholesky', 'sag',
                                     'saga']},
                         {'C': [100, 10, 2.9, 0.3, 0.72], 'penalty': ['l1'],
                          'solver': ['saga']},
                         {'C': [100, 10, 2.9, 0.3, 0.72],
                          'l1_ratio': [0.5, 0.7], 'penalty': ['elasticnet'],
                          'solver': ['saga']}],
             scoring='accuracy')

In [28]:
grid.fit(X_train,y_train)

ModuleNotFoundError: No module named '_posixsubprocess'

In [ ]:
grid.best_params_

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

In [ ]:
grid.best_score_

AttributeError: 'GridSearchCV' object has no attribute 'best_score_'

In [ ]:
y_pred = grid.predict(X_test)

NotFittedError: This GridSearchCV instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
score = accuracy_score(y_test,y_pred)
print(score)
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.8571428571428571
[[293  50]
 [ 50 307]]
              precision    recall  f1-score   support

           0       0.85      0.85      0.85       343
           1       0.86      0.86      0.86       357

    accuracy                           0.86       700
   macro avg       0.86      0.86      0.86       700
weighted avg       0.86      0.86      0.86       700

